version: '3'
services:
  mongo-db:
    image: mongo:4.2
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: universities
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - mongo-compose-network
  app:
    build: .
    container_name: university-test
    ports:
      - 3001:3001
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    logging:
        driver: 'json-file'
        options:
          max-size: '10m'
          max-file: '5'
    links:
      - mongo-db
    depends_on:
      - mongo-db
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge